{
 "archived": false,
 "branch": "main",
 "conda-forge.yml": {},
 "feedstock_name": "pytest-github-actions-annotate-failures",
 "hash_type": "sha256",
 "linux_64_meta_yaml": {
  "about": {
   "home": "https://github.com/pytest-dev/pytest-github-actions-annotate-failures",
   "license": "MIT",
   "license_file": "LICENSE",
   "summary": "pytest plugin to annotate failed tests with a workflow command for GitHub Actions"
  },
  "build": {
   "noarch": "python",
   "number": "0",
   "script": "/usr/share/miniconda3/envs/cf-scripts/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python -m pip install . -vv"
  },
  "extra": {
   "recipe-maintainers": [
    "bollwyvl"
   ]
  },
  "package": {
   "name": "pytest-github-actions-annotate-failures",
   "version": "0.1.8"
  },
  "requirements": {
   "host": [
    "pip",
    "python ==2.7|>=3.6"
   ],
   "run": [
    "pytest >=4.0.0",
    "python ==2.7|>=3.6"
   ]
  },
  "source": {
   "sha256": "2d6e6cb5f8d0aae4a27a20cc4e20fabd3199a121c57f44bc48fe28e372e0be23",
   "url": "https://pypi.io/packages/source/p/pytest-github-actions-annotate-failures/pytest-github-actions-annotate-failures-0.1.8.tar.gz"
  },
  "test": {
   "commands": [
    "python -m pip check"
   ],
   "imports": [
    "pytest_github_actions_annotate_failures"
   ],
   "requires": [
    "pip"
   ]
  }
 },
 "linux_64_requirements": {
  "build": {
   "__set__": true,
   "elements": []
  },
  "host": {
   "__set__": true,
   "elements": [
    "pip",
    "python"
   ]
  },
  "run": {
   "__set__": true,
   "elements": [
    "pytest",
    "python"
   ]
  },
  "test": {
   "__set__": true,
   "elements": [
    "pip"
   ]
  }
 },
 "meta_yaml": {
  "about": {
   "home": "https://github.com/pytest-dev/pytest-github-actions-annotate-failures",
   "license": "MIT",
   "license_file": "LICENSE",
   "summary": "pytest plugin to annotate failed tests with a workflow command for GitHub Actions"
  },
  "build": {
   "noarch": "python",
   "number": "0",
   "script": "/usr/share/miniconda3/envs/cf-scripts/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python -m pip install . -vv"
  },
  "extra": {
   "recipe-maintainers": [
    "bollwyvl"
   ]
  },
  "package": {
   "name": "pytest-github-actions-annotate-failures",
   "version": "0.1.8"
  },
  "requirements": {
   "host": [
    "pip",
    "python ==2.7|>=3.6"
   ],
   "run": [
    "pytest >=4.0.0",
    "python ==2.7|>=3.6"
   ]
  },
  "source": {
   "sha256": "2d6e6cb5f8d0aae4a27a20cc4e20fabd3199a121c57f44bc48fe28e372e0be23",
   "url": "https://pypi.io/packages/source/p/pytest-github-actions-annotate-failures/pytest-github-actions-annotate-failures-0.1.8.tar.gz"
  },
  "test": {
   "commands": [
    "python -m pip check"
   ],
   "imports": [
    "pytest_github_actions_annotate_failures"
   ],
   "requires": [
    "pip"
   ]
  }
 },
 "name": "pytest-github-actions-annotate-failures",
 "outputs_names": {
  "__set__": true,
  "elements": [
   "pytest-github-actions-annotate-failures"
  ]
 },
 "parsing_error": false,
 "pr_info": {
  "__lazy_json__": "pr_info/pytest-github-actions-annotate-failures.json"
 },
 "raw_meta_yaml": "{% set version = \"0.1.8\" %}\n\npackage:\n  name: pytest-github-actions-annotate-failures\n  version: {{ version }}\n\nsource:\n  url: https://pypi.io/packages/source/p/pytest-github-actions-annotate-failures/pytest-github-actions-annotate-failures-{{ version }}.tar.gz\n  sha256: 2d6e6cb5f8d0aae4a27a20cc4e20fabd3199a121c57f44bc48fe28e372e0be23\n\nbuild:\n  number: 0\n  noarch: python\n  script: {{ PYTHON }} -m pip install . -vv\n\nrequirements:\n  host:\n    - pip\n    - python ==2.7|>=3.6\n  run:\n    - pytest >=4.0.0\n    - python ==2.7|>=3.6\n\ntest:\n  imports:\n    - pytest_github_actions_annotate_failures\n  commands:\n    - python -m pip check\n  requires:\n    - pip\n\nabout:\n  home: https://github.com/pytest-dev/pytest-github-actions-annotate-failures\n  summary: pytest plugin to annotate failed tests with a workflow command for GitHub Actions\n  license: MIT\n  license_file: LICENSE\n\nextra:\n  recipe-maintainers:\n    - bollwyvl\n",
 "req": {
  "__set__": true,
  "elements": [
   "pip",
   "pytest",
   "python"
  ]
 },
 "requirements": {
  "build": {
   "__set__": true,
   "elements": []
  },
  "host": {
   "__set__": true,
   "elements": [
    "pip",
    "python"
   ]
  },
  "run": {
   "__set__": true,
   "elements": [
    "pytest",
    "python"
   ]
  },
  "test": {
   "__set__": true,
   "elements": [
    "pip"
   ]
  }
 },
 "strong_exports": false,
 "total_requirements": {
  "build": {
   "__set__": true,
   "elements": []
  },
  "host": {
   "__set__": true,
   "elements": [
    "pip",
    "python ==2.7|>=3.6"
   ]
  },
  "run": {
   "__set__": true,
   "elements": [
    "pytest >=4.0.0",
    "python ==2.7|>=3.6"
   ]
  },
  "test": {
   "__set__": true,
   "elements": [
    "pip"
   ]
  }
 },
 "url": "https://pypi.io/packages/source/p/pytest-github-actions-annotate-failures/pytest-github-actions-annotate-failures-0.1.8.tar.gz",
 "version": "0.1.8",
 "version_pr_info": {
  "__lazy_json__": "version_pr_info/pytest-github-actions-annotate-failures.json"
 }
}