{
 "base": {
  "repo": {
   "name": "pyerrors-feedstock"
  }
 },
 "closed_at": null,
 "created_at": "2023-06-02T18:10:34Z",
 "draft": false,
 "head": {
  "ref": "2.8.2_h58179a"
 },
 "html_url": "https://github.com/conda-forge/pyerrors-feedstock/pull/7",
 "id": 1376142470,
 "labels": [],
 "mergeable": null,
 "mergeable_state": "unknown",
 "merged": false,
 "merged_at": null,
 "number": 7,
 "state": "open",
 "updated_at": "2023-06-02T18:10:34Z"
}