{
 "PRed": [
  {
   "PR": {
    "number": 1,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python310"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 3,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "1.1.1"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 4,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python311"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2022.11.05.21.08.08",
 "pre_pr_migrator_attempts": {
  "pypy38": 13
 },
 "pre_pr_migrator_status": {
  "pypy38": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/5707374650\">bot CI job</a>): main: ['linux_64_python3.8.____73_pypy: Encountered problems while solving:\\n  - package tfs-pandas-3.0.2-pyhd8ed1ab_0 requires numpy >=1.19.0, but none of the providers can be installed', 'linux_64_python3.9.____73_pypy: Encountered problems while solving:\\n  - package tfs-pandas-3.0.2-pyhd8ed1ab_0 requires python >=3.6, but none of the providers can be installed', 'osx_64_python3.8.____73_pypy: Encountered problems while solving:\\n  - package tfs-pandas-3.0.2-pyhd8ed1ab_0 requires numpy >=1.19.0, but none of the providers can be installed', 'osx_64_python3.9.____73_pypy: Encountered problems while solving:\\n  - package tfs-pandas-3.0.2-pyhd8ed1ab_0 requires python >=3.6, but none of the providers can be installed']"
 },
 "smithy_version": "3.21.3"
}