{
  "done": [],
  "in-pr": [
    "mumps"
  ],
  "awaiting-pr": [],
  "not-solvable": [],
  "awaiting-parents": [
    "petsc",
    "fenics",
    "fenics-dolfinx"
  ],
  "bot-error": [
    "neper"
  ],
  "_feedstock_status": {
    "fenics": {
      "num_descendants": 1,
      "immediate_children": [
        "fenics-dolfinx"
      ],
      "pre_pr_migrator_status": ""
    },
    "mumps": {
      "num_descendants": 3,
      "immediate_children": [
        "petsc"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/mumps-feedstock/pull/84",
      "pr_status": "unstable"
    },
    "petsc": {
      "num_descendants": 2,
      "immediate_children": [
        "fenics",
        "fenics-dolfinx"
      ],
      "pre_pr_migrator_status": ""
    },
    "neper": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/4873132896\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1186, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 282, in run\n    eval_cmd(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 341, in eval_cmd\n    c.check_returncode()\n  File \"/usr/share/miniconda3/envs/cf-scripts/lib/python3.9/subprocess.py\", line 460, in check_returncode\n    raise CalledProcessError(self.returncode, self.args, self.stdout,\nsubprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.\n"
    },
    "fenics-dolfinx": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": ""
    }
  }
}